In [ ]:
#1) Read Laliga.csv file replace dashes with 0

In [124]:
import pandas as pd
import numpy as np

In [125]:
df=pd.read_csv('E:\python basics\Statistical learning Exam\Laliga.csv',na_values='-',skiprows=[0],sep=',')

In [126]:
df.fillna(0,inplace=True)
df

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1
5,6,Sevilla,73,2819.0,2408.0,990.0,531.0,887.0,3680.0,3373.0,1.0,4.0,4.0,5.0,12.0,6.0,32.0,1934-35,2001-02,1
6,7,Espanyol,82,2792.0,2626.0,948.0,608.0,1070.0,3609.0,3889.0,0.0,0.0,4.0,5.0,2.0,5.0,16.0,1929,1994-95,3
7,8,Real Sociedad,70,2573.0,2302.0,864.0,577.0,861.0,3228.0,3230.0,2.0,3.0,2.0,5.0,4.0,3.0,19.0,1929,2010-11,1
8,9,Zaragoza,58,2109.0,1986.0,698.0,522.0,766.0,2683.0,2847.0,0.0,1.0,4.0,5.0,4.0,4.0,18.0,1939-40,2012-13,2
9,10,Real Betis,51,1884.0,1728.0,606.0,440.0,682.0,2159.0,2492.0,1.0,0.0,2.0,3.0,4.0,4.0,14.0,1932-33,2015-16,1
10,11,Deportivo La Coruna,45,1814.0,1530.0,563.0,392.0,575.0,2052.0,2188.0,1.0,5.0,4.0,1.0,0.0,1.0,12.0,1941-42,2014-15,1
11,12,Celta Vigo,51,1789.0,1698.0,586.0,389.0,723.0,2278.0,2624.0,0.0,0.0,0.0,2.0,4.0,5.0,11.0,1939-40,2012-13,4
12,13,Valladolid,42,1471.0,1466.0,463.0,384.0,619.0,1767.0,2180.0,0.0,0.0,0.0,1.0,1.0,1.0,3.0,1948-49,2013-14,4
13,14,Racing Santander,44,1416.0,1428.0,453.0,336.0,639.0,1843.0,2368.0,0.0,1.0,1.0,2.0,0.0,1.0,5.0,1929,2011-12,2
14,15,Sporting Gijon,43,1389.0,1458.0,471.0,358.0,629.0,1753.0,2152.0,0.0,1.0,1.0,2.0,2.0,1.0,7.0,1944-45,2015-16,2
15,16,Osasuna,37,1351.0,1318.0,426.0,327.0,565.0,1500.0,1834.0,0.0,0.0,0.0,2.0,2.0,2.0,6.0,1935-36,2016-17,4
16,17,Malaga,36,1314.0,1255.0,390.0,330.0,535.0,1421.0,1763.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,1949-50,2008-09,4
17,18,Oviedo,38,1174.0,1192.0,408.0,292.0,492.0,1642.0,1951.0,0.0,0.0,3.0,2.0,2.0,4.0,11.0,1933-34,2000-01,3
18,19,Mallorca,27,1148.0,988.0,333.0,256.0,399.0,1182.0,1371.0,0.0,0.0,2.0,0.0,2.0,1.0,5.0,1960-61,2012-13,3
19,20,Las Palmas,33,1020.0,1096.0,367.0,242.0,487.0,1347.0,1746.0,0.0,1.0,1.0,1.0,1.0,1.0,5.0,1951-52,2015-16,2
20,21,Villarreal,17,970.0,646.0,266.0,172.0,208.0,892.0,789.0,0.0,1.0,1.0,2.0,3.0,2.0,9.0,1998-99,2013-14,2
21,22,Granada,23,667.0,742.0,218.0,175.0,349.0,819.0,1157.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1941-42,2016-17,6
22,23,Rayo Vallecano,17,662.0,652.0,189.0,148.0,305.0,760.0,1088.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1977-78,2015-16,8
23,24,Elche,21,606.0,678.0,203.0,180.0,295.0,750.0,1022.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1959-60,2014-15,5
24,25,Getafe,12,553.0,456.0,147.0,112.0,197.0,520.0,633.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2004-05,2015-16,6
25,26,Hercules,20,538.0,628.0,184.0,149.0,295.0,716.0,1050.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,1935-36,2010-11,5
26,27,Tenerife,13,510.0,494.0,155.0,128.0,211.0,619.0,744.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,1961-62,2009-10,5
27,28,Murcia,18,445.0,586.0,145.0,143.0,298.0,607.0,992.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1940-41,2007-08,11
28,29,Alaves,12,421.0,380.0,125.0,81.0,174.0,458.0,623.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1930-31,2016-17,6
29,30,Levante,11,416.0,402.0,113.0,95.0,194.0,430.0,632.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1963-64,2015-16,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,32,Sabadell,14,353.0,426.0,129.0,95.0,202.0,492.0,720.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,1943-44,1987-88,4
32,33,Cadiz,12,343.0,448.0,104.0,127.0,217.0,393.0,662.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1977-78,2005-06,12
33,34,Logrones,9,293.0,346.0,96.0,92.0,158.0,291.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1987-88,1996-97,7
34,35,Castellon,11,285.0,334.0,103.0,79.0,152.0,419.0,588.0,0.0,0.0,0.0,1.0,2.0,0.0,3.0,1941-42,1990-91,4
35,36,Albacete,7,277.0,270.0,76.0,76.0,118.0,320.0,410.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991-92,2004-05,7
36,37,Almeria,6,242.0,228.0,62.0,56.0,110.0,244.0,366.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2007-08,2014-15,8
37,38,Cordoba,9,230.0,282.0,82.0,63.0,137.0,285.0,430.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1962-63,2014-15,5
38,39,Compostela,4,190.0,160.0,52.0,45.0,63.0,199.0,241.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1994-95,1997-98,10
39,40,Recreativo,5,188.0,186.0,50.0,46.0,90.0,202.0,296.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1978-79,2008-09,8
40,41,Burgos CF,6,168.0,204.0,59.0,50.0,95.0,216.0,310.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1971-72,1979-80,12
41,42,Pontevedra,6,150.0,180.0,53.0,44.0,83.0,165.0,221.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1963-64,1969-70,7
42,43,Numancia,4,148.0,152.0,37.0,37.0,78.0,155.0,253.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1999-00,2008-09,17
43,44,Eibar,3,132.0,114.0,35.0,27.0,52.0,139.0,167.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-15,2014-15,10
44,45,Arenas,7,107.0,130.0,43.0,21.0,66.0,227.0,308.0,0.0,0.0,1.0,0.0,3.0,0.0,4.0,1929,1934-35,3
45,46,Real Burgos,3,96.0,114.0,26.0,44.0,44.0,101.0,139.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1990-91,1992-93,9
46,47,Gimnastic,4,91.0,116.0,34.0,16.0,66.0,181.0,295.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1947-48,2006-07,7
47,48,Extremadura,2,83.0,80.0,20.0,23.0,37.0,62.0,117.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1996-97,1998-99,17
48,49,Merida,2,81.0,80.0,19.0,24.0,37.0,70.0,115.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1995-96,1997-98,19
49,50,Alcoyano,4,76.0,108.0,30.0,16.0,62.0,145.0,252.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1945-46,1950-51,10
50,51,Jaen,3,71.0,90.0,29.0,13.0,48.0,121.0,183.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1953-54,1957-58,14
51,52,Real Union,4,56.0,72.0,21.0,14.0,37.0,153.0,184.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1929,1931-32,6
52,53,AD Almeria,2,52.0,68.0,17.0,18.0,33.0,71.0,116.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1979-80,1980-81,10
53,54,Europa,3,42.0,54.0,18.0,6.0,30.0,97.0,131.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1929,1930-31,8
54,55,Lleida,2,40.0,68.0,13.0,14.0,41.0,70.0,182.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1950-51,1993-94,16
55,56,Leganes,1,35.0,38.0,8.0,11.0,19.0,36.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2016-17,2016-17,17
56,57,Xerez,1,34.0,38.0,8.0,10.0,20.0,38.0,66.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2009-10,2009-10,20
57,58,Condal,1,22.0,30.0,7.0,8.0,15.0,37.0,57.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1956-57,1956-57,16
58,59,Atletico Tetuan,1,19.0,30.0,7.0,5.0,18.0,51.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1951-52,1951-52,16
59,60,Cultural Leonesa,1,14.0,30.0,5.0,4.0,21.0,34.0,65.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1955-56,1955-56,15
60,61,Girona,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-18,2017-18,9

In [127]:
# 2) Print all the team stated playing between 1930 - 1980

In [128]:
split_debut = df.loc[:,'Debut'].str.split('-',expand=True).fillna(0).astype(int)
split_debut['Team'] = df['Team']
split_debut.columns=['debut','to','team']
split_debut.drop(['to'],axis=1,inplace=True)
split_debut[(split_debut.debut >= 1930) & (split_debut.debut <= 1980)]   
#sorted_team

    debut                 team
3    1931             Valencia
5    1934              Sevilla
8    1939             Zaragoza
9    1932           Real Betis
10   1941  Deportivo La Coruna
11   1939           Celta Vigo
12   1948           Valladolid
14   1944       Sporting Gijon
15   1935              Osasuna
16   1949               Malaga
17   1933               Oviedo
18   1960             Mallorca
19   1951           Las Palmas
21   1941              Granada
22   1977       Rayo Vallecano
23   1959                Elche
25   1935             Hercules
26   1961             Tenerife
27   1940               Murcia
28   1930               Alaves
29   1963              Levante
30   1974            Salamanca
31   1943             Sabadell
32   1977                Cadiz
34   1941            Castellon
37   1962              Cordoba
39   1978           Recreativo
40   1971            Burgos CF
41   1963           Pontevedra
46   1947            Gimnastic
49   1945             Alcoyano
50   1953                 Jaen
52   1979           AD Almeria
54   1950               Lleida
57   1956               Condal
58   1951      Atletico Tetuan
59   1955     Cultural Leonesa

In [129]:
# 3)Print the list of team top five Among points.

In [130]:
df.sort_values('Points',ascending = False).head(5)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1

In [133]:
#4)
def Goal_diff_count(gf,ga):
    goal_diff = gf - ga.values
    return goal_diff
    
goal_diff = Goal_diff_count(df.iloc[:,8:9],df.iloc[:,9:10])

goal_diff['Goal Diffrence'] = goal_diff['GoalsFor']
goal_diff.drop(['GoalsFor'],axis=1,inplace=True)
max_count  = goal_diff.max()
min_count = goal_diff.min()
min_count =(-(min_count))
diff_max_min = Goal_diff_count(max_count,min_count)



print(diff_max_min)
goal_diff

Goal Diffrence    2282.0
dtype: float64

    Goal Diffrence
0           2807.0
1           2786.0
2           1225.0
3            929.0
4            931.0
5            307.0
6           -280.0
7             -2.0
8           -164.0
9           -333.0
10          -136.0
11          -346.0
12          -413.0
13          -525.0
14          -399.0
15          -334.0
16          -342.0
17          -309.0
18          -189.0
19          -399.0
20           103.0
21          -338.0
22          -328.0
23          -272.0
24          -113.0
25          -334.0
26          -125.0
27          -385.0
28          -165.0
29          -202.0
..             ...
31          -228.0
32          -269.0
33          -198.0
34          -169.0
35           -90.0
36          -122.0
37          -145.0
38           -42.0
39           -94.0
40           -94.0
41           -56.0
42           -98.0
43           -28.0
44           -81.0
45           -38.0
46          -114.0
47           -55.0
48           -45.0
49          -107.0
50           -62.0
51           -31.0
52           -45.0
53           -34.0
54          -112.0
55           -19.0
56           -28.0
57           -20.0
58           -34.0
59           -31.0
60             0.0

[61 rows x 1 columns]

In [181]:
#5)
df['WinningPercentage'] = (df[['GamesWon']] / df[['GamesPlayed']].values)*100
df.fillna(0)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,WinningPercentage
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,...,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1,59.630702
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,...,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1,57.241130
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,...,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1,47.475134
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,...,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1,44.557057
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,...,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1,43.772629
5,6,Sevilla,73,2819.0,2408.0,990.0,531.0,887.0,3680.0,3373.0,...,4.0,4.0,5.0,12.0,6.0,32.0,1934-35,2001-02,1,41.112957
6,7,Espanyol,82,2792.0,2626.0,948.0,608.0,1070.0,3609.0,3889.0,...,0.0,4.0,5.0,2.0,5.0,16.0,1929,1994-95,3,36.100533
7,8,Real Sociedad,70,2573.0,2302.0,864.0,577.0,861.0,3228.0,3230.0,...,3.0,2.0,5.0,4.0,3.0,19.0,1929,2010-11,1,37.532580
8,9,Zaragoza,58,2109.0,1986.0,698.0,522.0,766.0,2683.0,2847.0,...,1.0,4.0,5.0,4.0,4.0,18.0,1939-40,2012-13,2,35.146022
9,10,Real Betis,51,1884.0,1728.0,606.0,440.0,682.0,2159.0,2492.0,...,0.0,2.0,3.0,4.0,4.0,14.0,1932-33,2015-16,1,35.069444
10,11,Deportivo La Coruna,45,1814.0,1530.0,563.0,392.0,575.0,2052.0,2188.0,...,5.0,4.0,1.0,0.0,1.0,12.0,1941-42,2014-15,1,36.797386
11,12,Celta Vigo,51,1789.0,1698.0,586.0,389.0,723.0,2278.0,2624.0,...,0.0,0.0,2.0,4.0,5.0,11.0,1939-40,2012-13,4,34.511190
12,13,Valladolid,42,1471.0,1466.0,463.0,384.0,619.0,1767.0,2180.0,...,0.0,0.0,1.0,1.0,1.0,3.0,1948-49,2013-14,4,31.582538
13,14,Racing Santander,44,1416.0,1428.0,453.0,336.0,639.0,1843.0,2368.0,...,1.0,1.0,2.0,0.0,1.0,5.0,1929,2011-12,2,31.722689
14,15,Sporting Gijon,43,1389.0,1458.0,471.0,358.0,629.0,1753.0,2152.0,...,1.0,1.0,2.0,2.0,1.0,7.0,1944-45,2015-16,2,32.304527
15,16,Osasuna,37,1351.0,1318.0,426.0,327.0,565.0,1500.0,1834.0,...,0.0,0.0,2.0,2.0,2.0,6.0,1935-36,2016-17,4,32.321700
16,17,Malaga,36,1314.0,1255.0,390.0,330.0,535.0,1421.0,1763.0,...,0.0,0.0,1.0,0.0,1.0,2.0,1949-50,2008-09,4,31.075697
17,18,Oviedo,38,1174.0,1192.0,408.0,292.0,492.0,1642.0,1951.0,...,0.0,3.0,2.0,2.0,4.0,11.0,1933-34,2000-01,3,34.228188
18,19,Mallorca,27,1148.0,988.0,333.0,256.0,399.0,1182.0,1371.0,...,0.0,2.0,0.0,2.0,1.0,5.0,1960-61,2012-13,3,33.704453
19,20,Las Palmas,33,1020.0,1096.0,367.0,242.0,487.0,1347.0,1746.0,...,1.0,1.0,1.0,1.0,1.0,5.0,1951-52,2015-16,2,33.485401
20,21,Villarreal,17,970.0,646.0,266.0,172.0,208.0,892.0,789.0,...,1.0,1.0,2.0,3.0,2.0,9.0,1998-99,2013-14,2,41.176471
21,22,Granada,23,667.0,742.0,218.0,175.0,349.0,819.0,1157.0,...,0.0,0.0,0.0,0.0,2.0,2.0,1941-42,2016-17,6,29.380054
22,23,Rayo Vallecano,17,662.0,652.0,189.0,148.0,305.0,760.0,1088.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1977-78,2015-16,8,28.987730
23,24,Elche,21,606.0,678.0,203.0,180.0,295.0,750.0,1022.0,...,0.0,0.0,0.0,1.0,1.0,2.0,1959-60,2014-15,5,29.941003
24,25,Getafe,12,553.0,456.0,147.0,112.0,197.0,520.0,633.0,...,0.0,0.0,0.0,0.0,1.0,1.0,2004-05,2015-16,6,32.236842
25,26,Hercules,20,538.0,628.0,184.0,149.0,295.0,716.0,1050.0,...,0.0,0.0,0.0,1.0,4.0,5.0,1935-36,2010-11,5,29.299363
26,27,Tenerife,13,510.0,494.0,155.0,128.0,211.0,619.0,744.0,...,0.0,0.0,0.0,2.0,0.0,2.0,1961-62,2009-10,5,31.376518
27,28,Murcia,18,445.0,586.0,145.0,143.0,298.0,607.0,992.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1940-41,2007-08,11,24.744027
28,29,Alaves,12,421.0,380.0,125.0,81.0,174.0,458.0,623.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1930-31,2016-17,6,32.894737
29,30,Levante,11,416.0,402.0,113.0,95.0,194.0,430.0,632.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1963-64,2015-16,6,28.109453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,32,Sabadell,14,353.0,426.0,129.0,95.0,202.0,492.0,720.0,...,0.0,0.0,1.0,1.0,0.0,2.0,1943-44,1987-88,4,30.281690
32,33,Cadiz,12,343.0,448.0,104.0,127.0,217.0,393.0,662.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1977-78,2005-06,12,23.214286
33,34,Logrones,9,293.0,346.0,96.0,92.0,158.0,291.0,489.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1987-88,1996-97,7,27.745665
34,35,Castellon,11,285.0,334.0,103.0,79.0,152.0,419.0,588.0,...,0.0,0.0,1.0,2.0,0.0,3.0,1941-42,1990-91,4,30.838323
35,36,Albacete,7,277.0,270.0,76.0,76.0,118.0,320.0,410.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1991-92,2004-05,7,28.148148
36,37,Almeria,6,242.0,228.0,62.0,56.0,110.0,244.0,366.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2007-08,2014-15,8,27.192982
37,38,Cordoba,9,230.0,282.0,82.0,63.0,137.0,285.0,430.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1962-63,2014-15,5,29.078014
38,39,Compostela,4,190.0,160.0,52.0,45.0,63.0,199.0,241.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1994-95,1997-98,10,32.500000
39,40,Recreativo,5,188.0,186.0,50.0,46.0,90.0,202.0,296.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1978-79,2008-09,8,26.881720
40,41,Burgos CF,6,168.0,204.0,59.0,50.0,95.0,216.0,310.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1971-72,1979-80,12,28.921569
41,42,Pontevedra,6,150.0,180.0,53.0,44.0,83.0,165.0,221.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1963-64,1969-70,7,29.444444
42,43,Numancia,4,148.0,152.0,37.0,37.0,78.0,155.0,253.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1999-00,2008-09,17,24.342105
43,44,Eibar,3,132.0,114.0,35.0,27.0,52.0,139.0,167.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2014-15,2014-15,10,30.701754
44,45,Arenas,7,107.0,130.0,43.0,21.0,66.0,227.0,308.0,...,0.0,1.0,0.0,3.0,0.0,4.0,1929,1934-35,3,33.076923
45,46,Real Burgos,3,96.0,114.0,26.0,44.0,44.0,101.0,139.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1990-91,1992-93,9,22.807018
46,47,Gimnastic,4,91.0,116.0,34.0,16.0,66.0,181.0,295.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1947-48,2006-07,7,29.310345
47,48,Extremadura,2,83.0,80.0,20.0,23.0,37.0,62.0,117.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1996-97,1998-99,17,25.000000
48,49,Merida,2,81.0,80.0,19.0,24.0,37.0,70.0,115.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1995-96,1997-98,19,23.750000
49,50,Alcoyano,4,76.0,108.0,30.0,16.0,62.0,145.0,252.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1945-46,1950-51,10,27.777778
50,51,Jaen,3,71.0,90.0,29.0,13.0,48.0,121.0,183.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1953-54,1957-58,14,32.222222
51,52,Real Union,4,56.0,72.0,21.0,14.0,37.0,153.0,184.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1929,1931-32,6,29.166667
52,53,AD Almeria,2,52.0,68.0,17.0,18.0,33.0,71.0,116.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1979-80,1980-81,10,25.000000
53,54,Europa,3,42.0,54.0,18.0,6.0,30.0,97.0,131.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1929,1930-31,8,33.333333
54,55,Lleida,2,40.0,68.0,13.0,14.0,41.0,70.0,182.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1950-51,1993-94,16,19.117647
55,56,Leganes,1,35.0,38.0,8.0,11.0,19.0,36.0,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2016-17,2016-17,17,21.052632
56,57,Xerez,1,34.0,38.0,8.0,10.0,20.0,38.0,66.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2009-10,2009-10,20,21.052632
57,58,Condal,1,22.0,30.0,7.0,8.0,15.0,37.0,57.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1956-57,1956-57,16,23.333333
58,59,Atletico Tetuan,1,19.0,30.0,7.0,5.0,18.0,51.0,85.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1951-52,1951-52,16,23.333333
59,60,Cultural Leonesa,1,14.0,30.0,5.0,4.0,21.0,34.0,65.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1955-56,1955-56,15,16.666667
60,61,Girona,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2017-18,2017-18,9,0.000000

In [189]:
#Top Five team having higest Percentage.
top = df.sort_values('WinningPercentage',ascending = False).head(5)
team = top.loc[:,'Team']
team

0        Real Madrid
1          Barcelona
2    Atletico Madrid
3           Valencia
4    Athletic Bilbao
Name: Team, dtype: object

In [137]:
#6) Group by best position and print the sum of their points for all positions.
df.groupby(['Pos','Points']).sum().head(2)

,,Seasons,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,BestPosition
Pos,Points,,,,,,,,,,,,,,,
1,4385.0,86,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1
2,4262.0,86,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1